# Generated by Django 3.0 on 2020-04-20 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=30)),
                ('image', models.ImageField(default=None, upload_to='images/realtors')),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('House_Title', models.CharField(max_length=50)),
                ('House_Address', models.CharField(max_length=500)),
                ('house_Desc', models.CharField(max_length=1000)),
                ('Price', models.IntegerField(default=0)),
                ('House_Area', models.IntegerField(default=0)),
                ('No_of_rooms', models.IntegerField(default=0)),
                ('Garrage', models.BooleanField(default=False)),
                ('Main_Photo', models.ImageField(default=None, upload_to='images/homes')),
                ('Inside_Photo', models.ImageField(default=None, upload_to='images/homes')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Realtor')),
            ],
        ),
    ]
